json.uid @transaction.uid
json.from @transaction.sender_email
json.to @transaction.recipient_email
json.amount @transaction.amount
json.currency @transaction.currency
json.references @transaction.references
json.(@transaction, :created_at)
json.url @transaction.url
json.status @transaction.status